---
- name: Frappe Health Check
  hosts: frappe
  gather_facts: no

  tasks:
    - name: Check bench version
      shell: |
        cd ~/frappe-bench
        bench version
      register: bench_version

    - name: Display version
      debug:
        var: bench_version.stdout_lines
